//! Conformance runner for the committed format v2 vectors.
//!
//! This is what makes the specification meaningful rather than merely
//! descriptive. The vectors in `fixtures/format-v2/` are bytes and expected
//! verdicts, generated by the Go reference implementation and committed. If
//! this Rust implementation disagrees about a single byte or a single verdict,
//! the run fails — and because the vectors are inputs rather than code, neither
//! implementation can quietly drag the other along.
//!
//! The firmware will be checked the same way, and it is the implementation that
//! matters most: a disagreement there would mean a device writing bundles the
//! server cannot recover.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use ed25519_dalek::VerifyingKey;
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::format::{
    self, Manifest, Member, Receipt, ScanState, content_root, manifest::verify_manifest,
    merkle_root, scan_segment,
};

#[derive(Debug, Deserialize)]
struct Expectation {
    name: String,
    #[allow(dead_code)]
    description: String,

    scan: Option<ScanExpectation>,
    header: Option<HeaderExpectation>,
    manifest: Option<ManifestExpectation>,
    receipt: Option<ReceiptExpectation>,
    merkle: Option<MerkleExpectation>,
}

#[derive(Debug, Deserialize)]
struct ScanExpectation {
    stop_reason: String,
    frames_retained: usize,
    stop_offset: usize,
    discarded_tail_bytes: u32,
    unknown_type_count: usize,
    record_counts: BTreeMap<String, usize>,
    first_seq: Option<u32>,
    last_seq: Option<u32>,
}

#[derive(Debug, Deserialize)]
struct HeaderExpectation {
    #[allow(dead_code)]
    parse_error: String,
}

#[derive(Debug, Deserialize)]
struct ManifestExpectation {
    valid: bool,
    signature_valid: bool,
    content_root_hex: String,
    device_public_key_hex: String,
    #[serde(default)]
    canonical_bytes_sha256_hex: String,
}

#[derive(Debug, Deserialize)]
struct ReceiptExpectation {
    signature_valid: bool,
    acknowledges_uploaded_root: bool,
    uploaded_content_root_hex: String,
    #[allow(dead_code)]
    receipt_content_root_hex: String,
    server_public_key_hex: String,
}

#[derive(Debug, Deserialize)]
struct MerkleExpectation {
    root_hex: String,
    #[serde(default)]
    leaves_hex: Option<Vec<String>>,
}

/// A multi-segment vector uses a different shape: several scan expectations
/// threaded in order.
#[derive(Debug, Deserialize)]
struct MultiSegmentExpectation {
    name: String,
    segments: Vec<ScanExpectation>,
}

#[derive(Debug, Deserialize)]
struct MemberDescriptor {
    name: String,
    length: u64,
    sha256_hex: String,
}

/// Outcome of a conformance run.
pub struct Report {
    pub checked: usize,
    pub passed: usize,
    pub failures: Vec<String>,
    pub skipped: Vec<String>,
}

impl Report {
    pub fn ok(&self) -> bool {
        self.failures.is_empty() && self.checked > 0
    }
}

/// Run every vector in `dir`.
pub fn run(dir: &Path) -> std::io::Result<Report> {
    let mut report = Report {
        checked: 0,
        passed: 0,
        failures: Vec::new(),
        skipped: Vec::new(),
    };

    let mut entries: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.path())
        .collect();
    entries.sort();

    for vdir in entries {
        let name = vdir.file_name().unwrap().to_string_lossy().to_string();
        let expected_path = vdir.join("expected.json");

        let raw = match fs::read_to_string(&expected_path) {
            Ok(r) => r,
            Err(e) => {
                report
                    .failures
                    .push(format!("{name}: no expected.json: {e}"));
                continue;
            }
        };

        report.checked += 1;

        // Multi-segment vectors have their own shape; try it first.
        if let Ok(multi) = serde_json::from_str::<MultiSegmentExpectation>(&raw)
            && !multi.segments.is_empty()
        {
            match check_multi_segment(&vdir, &multi) {
                Ok(()) => report.passed += 1,
                Err(why) => report.failures.push(format!("{}: {why}", multi.name)),
            }
            continue;
        }

        let exp: Expectation = match serde_json::from_str(&raw) {
            Ok(e) => e,
            Err(e) => {
                report
                    .failures
                    .push(format!("{name}: unparseable expected.json: {e}"));
                continue;
            }
        };

        let result = if exp.scan.is_some() {
            check_scan(&vdir, &exp)
        } else if exp.header.is_some() {
            check_header(&vdir)
        } else if exp.manifest.is_some() {
            check_manifest(&vdir, &exp)
        } else if exp.receipt.is_some() {
            check_receipt(&vdir, &exp)
        } else if exp.merkle.is_some() {
            check_merkle(&vdir, &exp)
        } else {
            report.skipped.push(exp.name.clone());
            report.checked -= 1;
            continue;
        };

        match result {
            Ok(()) => report.passed += 1,
            Err(why) => report.failures.push(format!("{}: {why}", exp.name)),
        }
    }

    Ok(report)
}

fn check_scan(dir: &Path, exp: &Expectation) -> std::result::Result<(), String> {
    let scan = exp.scan.as_ref().unwrap();
    let bytes = fs::read(dir.join("segment.bin")).map_err(|e| format!("read segment.bin: {e}"))?;

    let res = scan_segment(&bytes, ScanState::default())
        .map_err(|e| format!("scan_segment returned an error: {e}"))?;

    compare_scan(&res, scan, "")
}

fn check_multi_segment(
    dir: &Path,
    multi: &MultiSegmentExpectation,
) -> std::result::Result<(), String> {
    let mut state = ScanState::default();

    for (i, expected) in multi.segments.iter().enumerate() {
        let path = dir.join(format!("segment-{i}.bin"));
        let bytes = fs::read(&path).map_err(|e| format!("read {}: {e}", path.display()))?;

        let res = scan_segment(&bytes, state)
            .map_err(|e| format!("segment {i}: scan returned an error: {e}"))?;

        compare_scan(&res, expected, &format!("segment {i}: "))?;
        state = res.next;
    }

    // Scanning the second segment from a zero state must be detected as a
    // chain break rather than silently accepted: the chain runs bundle-wide.
    if multi.segments.len() > 1 {
        let bytes = fs::read(dir.join("segment-1.bin")).map_err(|e| e.to_string())?;
        let res = scan_segment(&bytes, ScanState::default()).map_err(|e| e.to_string())?;
        if res.stop != format::StopReason::ChainBreak {
            return Err(format!(
                "scanning segment 1 from a zero state gave {}, want CHAIN_BREAK",
                res.stop
            ));
        }
    }

    Ok(())
}

fn compare_scan(
    res: &format::ScanResult,
    exp: &ScanExpectation,
    prefix: &str,
) -> std::result::Result<(), String> {
    if res.stop.name() != exp.stop_reason {
        return Err(format!(
            "{prefix}stop_reason = {}, want {} ({})",
            res.stop.name(),
            exp.stop_reason,
            res.stop_detail
        ));
    }
    if res.frames.len() != exp.frames_retained {
        return Err(format!(
            "{prefix}frames_retained = {}, want {}",
            res.frames.len(),
            exp.frames_retained
        ));
    }
    if res.stop_offset != exp.stop_offset {
        return Err(format!(
            "{prefix}stop_offset = {}, want {}",
            res.stop_offset, exp.stop_offset
        ));
    }
    if res.discarded_tail_bytes != exp.discarded_tail_bytes {
        return Err(format!(
            "{prefix}discarded_tail_bytes = {}, want {}",
            res.discarded_tail_bytes, exp.discarded_tail_bytes
        ));
    }
    if res.unknown_type_count != exp.unknown_type_count {
        return Err(format!(
            "{prefix}unknown_type_count = {}, want {}",
            res.unknown_type_count, exp.unknown_type_count
        ));
    }

    for (name, want) in &exp.record_counts {
        let got = res
            .record_counts
            .iter()
            .find(|(rt, _)| &rt.name() == name)
            .map(|(_, n)| *n)
            .unwrap_or(0);
        if got != *want {
            return Err(format!(
                "{prefix}record_counts[{name}] = {got}, want {want}"
            ));
        }
    }

    if let Some(want) = exp.first_seq {
        match res.frames.first() {
            None => return Err(format!("{prefix}expected frames, got none")),
            Some(f) if f.seq != want => {
                return Err(format!("{prefix}first_seq = {}, want {want}", f.seq));
            }
            _ => {}
        }
    }
    if let (Some(want), Some(f)) = (exp.last_seq, res.frames.last())
        && f.seq != want
    {
        return Err(format!("{prefix}last_seq = {}, want {want}", f.seq));
    }

    Ok(())
}

fn check_header(dir: &Path) -> std::result::Result<(), String> {
    let bytes = fs::read(dir.join("segment.bin")).map_err(|e| format!("read segment.bin: {e}"))?;

    match scan_segment(&bytes, ScanState::default()) {
        Err(_) => Ok(()),
        Ok(_) => Err("expected a header parse error, got none".into()),
    }
}

fn check_manifest(dir: &Path, exp: &Expectation) -> std::result::Result<(), String> {
    let m_exp = exp.manifest.as_ref().unwrap();

    let encoded =
        fs::read(dir.join("manifest.cbor")).map_err(|e| format!("read manifest.cbor: {e}"))?;
    let sig_raw =
        fs::read(dir.join("manifest.sig")).map_err(|e| format!("read manifest.sig: {e}"))?;

    let sig: [u8; 64] = sig_raw
        .try_into()
        .map_err(|_| "manifest.sig is not 64 bytes".to_string())?;

    let key_bytes = format::unhex_array::<32>(&m_exp.device_public_key_hex)
        .ok_or("device_public_key_hex is not 32 bytes of hex")?;
    let key = VerifyingKey::from_bytes(&key_bytes).map_err(|e| format!("bad public key: {e}"))?;

    // The bytes must parse as canonical regardless of signature validity: a bad
    // signature does not make the encoding malformed.
    let parsed = Manifest::from_cbor(&encoded);
    match &parsed {
        Err(e) if m_exp.valid => return Err(format!("from_cbor: {e}")),
        _ => {}
    }

    match verify_manifest(&encoded, &sig, &key) {
        Err(e) if m_exp.signature_valid => return Err(format!("signature should verify: {e}")),
        Ok(_) if !m_exp.signature_valid => {
            return Err("signature verified but the vector expects it to fail".into());
        }
        _ => {}
    }

    let Ok(m) = parsed else { return Ok(()) };

    let want_root = format::unhex_array::<32>(&m_exp.content_root_hex)
        .ok_or("content_root_hex is not 32 bytes of hex")?;
    if m.content_root != want_root {
        return Err(format!(
            "content_root = {}, want {}",
            format::hex(&m.content_root),
            m_exp.content_root_hex
        ));
    }
    m.verify_content_root()
        .map_err(|e| format!("verify_content_root: {e}"))?;

    // Re-encoding must reproduce the committed bytes exactly. This is the check
    // that catches an accidental encoding divergence between implementations.
    if !m_exp.canonical_bytes_sha256_hex.is_empty() {
        let reencoded = m.to_cbor().map_err(|e| format!("to_cbor: {e}"))?;
        let digest = Sha256::digest(&reencoded);
        let got = format::hex(&digest);
        if got != m_exp.canonical_bytes_sha256_hex {
            return Err(format!(
                "re-encoded manifest digest = {got}, want {} — this implementation \
                 does not produce byte-identical output",
                m_exp.canonical_bytes_sha256_hex
            ));
        }
    }

    Ok(())
}

fn check_receipt(dir: &Path, exp: &Expectation) -> std::result::Result<(), String> {
    let r_exp = exp.receipt.as_ref().unwrap();

    let encoded =
        fs::read(dir.join("receipt.cbor")).map_err(|e| format!("read receipt.cbor: {e}"))?;

    let key_bytes = format::unhex_array::<32>(&r_exp.server_public_key_hex)
        .ok_or("server_public_key_hex is not 32 bytes of hex")?;
    let key = VerifyingKey::from_bytes(&key_bytes).map_err(|e| format!("bad public key: {e}"))?;

    let r = Receipt::from_cbor(&encoded).map_err(|e| format!("from_cbor: {e}"))?;

    let sig_ok = r.verify(&key).is_ok();
    if r_exp.signature_valid && !sig_ok {
        return Err("signature should verify".into());
    }
    if !r_exp.signature_valid && sig_ok {
        return Err("signature verified but the vector expects it to fail".into());
    }

    let uploaded = format::unhex_array::<32>(&r_exp.uploaded_content_root_hex)
        .ok_or("uploaded_content_root_hex is not 32 bytes of hex")?;

    let ack_ok = r.verify_acknowledges(&key, &uploaded).is_ok();
    if r_exp.acknowledges_uploaded_root && !ack_ok {
        return Err("receipt should acknowledge the upload".into());
    }
    if !r_exp.acknowledges_uploaded_root && ack_ok {
        return Err(
            "receipt accepted as an acknowledgement but the vector expects rejection".into(),
        );
    }

    Ok(())
}

fn check_merkle(dir: &Path, exp: &Expectation) -> std::result::Result<(), String> {
    let m_exp = exp.merkle.as_ref().unwrap();

    // Leaves present: check the tree construction directly.
    if let Some(leaves_hex) = &m_exp.leaves_hex {
        let mut leaves = Vec::with_capacity(leaves_hex.len());
        for h in leaves_hex {
            leaves.push(format::unhex_array::<32>(h).ok_or("leaf is not 32 bytes of hex")?);
        }

        let root = merkle_root(&leaves);
        let got = format::hex(&root);
        if got != m_exp.root_hex {
            return Err(format!("root = {got}, want {}", m_exp.root_hex));
        }
        return Ok(());
    }

    // Otherwise it is a content-root vector described by members.json.
    let raw = fs::read_to_string(dir.join("members.json"))
        .map_err(|e| format!("read members.json: {e}"))?;
    let descriptors: Vec<MemberDescriptor> =
        serde_json::from_str(&raw).map_err(|e| format!("parse members.json: {e}"))?;

    let mut members = Vec::with_capacity(descriptors.len());
    for d in &descriptors {
        members.push(Member {
            name: d.name.clone(),
            length: d.length,
            sha256: format::unhex_array::<32>(&d.sha256_hex)
                .ok_or("member sha256_hex is not 32 bytes of hex")?,
        });
    }

    let root = content_root(&members).map_err(|e| format!("content_root: {e}"))?;
    let got = format::hex(&root);
    if got != m_exp.root_hex {
        return Err(format!("content root = {got}, want {}", m_exp.root_hex));
    }

    // Order independence: a permuted input must yield the same root.
    if members.len() > 2 {
        let permuted = vec![members[2].clone(), members[0].clone(), members[1].clone()];
        let permuted_root = content_root(&permuted).map_err(|e| e.to_string())?;
        if permuted_root != root {
            return Err("permuted members produced a different content root".into());
        }
    }

    Ok(())
}
