//! Conformance runner for the committed format v3 vectors.
//!
//! This is what makes the specification meaningful rather than merely
//! descriptive. The vectors in `contracts/format/v3/vectors/` are bytes and expected
//! verdicts, generated by the Go reference implementation and committed. If
//! this Rust implementation disagrees about a single byte or a single verdict,
//! the run fails — and because the vectors are inputs rather than code, neither
//! implementation can quietly drag the other along.
//!
//! Every segment vector states two verdicts, and both are checked:
//!
//! - **structural** (`scan`): no key. Torn tails, CRCs, the chain and the
//!   sequence are computed over ciphertext, so this is the verdict anyone
//!   holding the bytes gets. A structural scan must also expose no plaintext.
//! - **keyed** (`keyed`): with K_root version 1 from `keys.json`. Adds the
//!   authentication of every frame, the derived segment key (checked separately
//!   from the AEAD so a KDF regression is reported as that), and a digest of
//!   the recovered plaintext.
//!
//! There is no skip path. A vector this runner does not recognise is a
//! failure: a vector nobody runs looks exactly like a vector that passes, and
//! that silent gap is the drift the committed vectors exist to prevent.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use ed25519_dalek::VerifyingKey;
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::format::{
    self, FormatError, KeyProvider, Manifest, Member, Receipt, RootKeyProvider, ScanResult,
    ScanState, StopReason, content_root, derive_segment_key, manifest::verify_manifest,
    merkle_root, payload, policy::PolicySnapshot, scan_segment, update::verify_update_descriptor,
    verify_members_against_manifest,
};

type Check = std::result::Result<(), String>;

// ── expectation shapes ──────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Expectation {
    name: String,

    scan: Option<ScanExpectation>,
    keyed: Option<KeyedExpectation>,

    // Multi-segment vectors. Their `keyed` is the array form of the field above.
    segments: Option<Vec<ScanExpectation>>,
    segment_1_from_zero_state: Option<ScanExpectation>,

    header: Option<HeaderExpectation>,
    manifest: Option<ManifestExpectation>,
    binding: Option<BindingExpectation>,
    receipt: Option<ReceiptExpectation>,
    merkle: Option<MerkleExpectation>,
    policy: Option<PolicySnapshot>,
    update: Option<UpdateExpectation>,
    events: Option<EventsExpectation>,
    health: Option<HealthExpectation>,
    obd_ext: Option<ObdExtExpectation>,
}

/// `keyed` is an object for single-segment vectors and an array for the
/// multi-segment one, so it is read through this untagged wrapper.
#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum KeyedExpectation {
    One(KeyedVerdict),
    Many(Vec<KeyedVerdict>),
}

#[derive(Debug, Deserialize)]
struct ScanExpectation {
    stop_reason: String,
    frames_retained: usize,
    stop_offset: usize,
    discarded_tail_bytes: u32,
    unknown_type_count: usize,
    record_counts: BTreeMap<String, usize>,
    first_seq: Option<u32>,
    last_seq: Option<u32>,
}

#[derive(Debug, Deserialize)]
struct KeyedVerdict {
    /// Set instead of the scan fields when the segment cannot be keyed at all.
    error: Option<String>,
    segment_key_hex: Option<String>,
    stop_reason: Option<String>,
    frames_retained: Option<usize>,
    stop_offset: Option<usize>,
    plaintext_sha256_hex: Option<String>,
}

#[derive(Debug, Deserialize)]
struct HeaderExpectation {
    parse_error: String,
}

#[derive(Debug, Deserialize)]
struct ManifestExpectation {
    valid: bool,
    signature_valid: bool,
    content_root_hex: String,
    device_public_key_hex: String,
    #[serde(default)]
    canonical_bytes_sha256_hex: String,
}

#[derive(Debug, Deserialize)]
struct BindingExpectation {
    #[serde(rename = "match")]
    matches: bool,
    #[serde(default)]
    mismatched_field: String,
}

#[derive(Debug, Deserialize)]
struct ReceiptExpectation {
    signature_valid: bool,
    acknowledges_uploaded_root: bool,
    uploaded_content_root_hex: String,
    receipt_content_root_hex: String,
    server_public_key_hex: String,
}

#[derive(Debug, Deserialize)]
struct MerkleExpectation {
    root_hex: String,
    #[serde(default)]
    leaves_hex: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
struct UpdateExpectation {
    signature_valid: bool,
    firmware_version: String,
    min_firmware_version: String,
    image_sha256_hex: String,
    image_length: u32,
    update_public_key_hex: String,
}

#[derive(Debug, Deserialize)]
struct EventsExpectation {
    events: Vec<EventExpectation>,
}

#[derive(Debug, Deserialize)]
struct EventExpectation {
    event_type: u8,
    event_type_name: String,
    lat_e7: i32,
    lon_e7: i32,
    detail: String,
}

#[derive(Debug, Deserialize)]
struct HealthExpectation {
    records: Vec<HealthRecordExpectation>,
}

#[derive(Debug, Deserialize)]
struct HealthRecordExpectation {
    health_state: u8,
    names: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ObdExtExpectation {
    records: Vec<ObdExtRecordExpectation>,
}

#[derive(Debug, Deserialize)]
struct ObdExtRecordExpectation {
    map_kpa: Option<u16>,
    maf_cgps: Option<u16>,
    lambda_e4: Option<u16>,
    abs_load_raw: Option<u16>,
    baro_kpa: Option<u8>,
    ambient_temp_c: Option<i8>,
    fuel_trim_short_pct: Option<i8>,
    fuel_trim_long_pct: Option<i8>,
    pids_requested: u32,
    pids_answered: u32,
    poll_cadence_ms: u16,
    map_saturated: bool,
    boost_psi: Option<f64>,
    lambda: Option<f64>,
    abs_load_pct: Option<f64>,
}

#[derive(Debug, Deserialize)]
struct MemberDescriptor {
    name: String,
    length: u64,
    sha256_hex: String,
}

#[derive(Debug, Deserialize)]
struct KeysFile {
    root_key_hex: String,
    storage_key_version: u32,
}

// ── report ──────────────────────────────────────────────────────────────────

/// Outcome of a conformance run.
pub struct Report {
    pub checked: usize,
    pub passed: usize,
    /// Segment verdicts checked without a key (one per segment scanned).
    pub structural_verdicts: usize,
    /// Segment verdicts checked with the vector key, including refusals.
    pub keyed_verdicts: usize,
    /// One line per passing vector, naming what was checked.
    pub passes: Vec<String>,
    pub failures: Vec<String>,
}

impl Report {
    pub fn ok(&self) -> bool {
        self.failures.is_empty() && self.checked > 0
    }
}

/// What one vector exercised, for the report.
#[derive(Default)]
struct Tally {
    structural: usize,
    keyed: usize,
    what: Vec<&'static str>,
}

/// Run every vector in `dir`.
pub fn run(dir: &Path) -> std::io::Result<Report> {
    let keys = load_keys(dir)?;

    let mut report = Report {
        checked: 0,
        passed: 0,
        structural_verdicts: 0,
        keyed_verdicts: 0,
        passes: Vec::new(),
        failures: Vec::new(),
    };

    let mut entries: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.path())
        .collect();
    entries.sort();

    for vdir in entries {
        let name = vdir.file_name().unwrap().to_string_lossy().to_string();
        report.checked += 1;

        let raw = match fs::read_to_string(vdir.join("expected.json")) {
            Ok(r) => r,
            Err(e) => {
                report
                    .failures
                    .push(format!("{name}: no expected.json: {e}"));
                continue;
            }
        };
        let exp: Expectation = match serde_json::from_str(&raw) {
            Ok(e) => e,
            Err(e) => {
                report
                    .failures
                    .push(format!("{name}: unparseable expected.json: {e}"));
                continue;
            }
        };

        let mut tally = Tally::default();
        match check_vector(&vdir, &exp, &keys, &mut tally) {
            Ok(()) => {
                report.passed += 1;
                report.structural_verdicts += tally.structural;
                report.keyed_verdicts += tally.keyed;
                report
                    .passes
                    .push(format!("{} — {}", exp.name, tally.what.join(", ")));
            }
            Err(why) => report.failures.push(format!("{}: {why}", exp.name)),
        }
    }

    Ok(report)
}

fn load_keys(dir: &Path) -> std::io::Result<RootKeyProvider> {
    let raw = fs::read_to_string(dir.join("keys.json"))?;
    let k: KeysFile = serde_json::from_str(&raw).map_err(std::io::Error::other)?;
    let root = format::unhex_array::<32>(&k.root_key_hex)
        .ok_or_else(|| std::io::Error::other("keys.json root_key_hex is not 32 bytes of hex"))?;
    Ok(RootKeyProvider::new(root, k.storage_key_version))
}

/// Dispatch on the sections the expectation carries. Several may apply to one
/// vector (a segment vector with payload expectations; a manifest vector with a
/// binding expectation), and every one present is checked.
fn check_vector(dir: &Path, exp: &Expectation, keys: &RootKeyProvider, t: &mut Tally) -> Check {
    let mut recognised = false;

    if let Some(scan) = &exp.scan {
        recognised = true;
        check_single_segment(dir, scan, exp.keyed.as_ref(), keys, t)?;
    }
    if let Some(segs) = &exp.segments {
        recognised = true;
        check_multi_segment(dir, segs, exp, keys, t)?;
    }
    if let Some(h) = &exp.header {
        recognised = true;
        check_header(dir, h, keys, t)?;
    }
    if let Some(m) = &exp.manifest {
        recognised = true;
        check_manifest(dir, m, t)?;
    }
    if let Some(b) = &exp.binding {
        recognised = true;
        check_binding(dir, b, t)?;
    }
    if let Some(r) = &exp.receipt {
        recognised = true;
        check_receipt(dir, r, t)?;
    }
    if let Some(m) = &exp.merkle {
        recognised = true;
        check_merkle(dir, m, t)?;
    }
    if let Some(p) = &exp.policy {
        recognised = true;
        check_policy(dir, p, t)?;
    }
    if let Some(u) = &exp.update {
        recognised = true;
        check_update(dir, u, t)?;
    }
    if let Some(e) = &exp.events {
        recognised = true;
        check_events(dir, e, keys, t)?;
    }
    if let Some(h) = &exp.health {
        recognised = true;
        check_health(dir, h, keys, t)?;
    }
    if let Some(o) = &exp.obd_ext {
        recognised = true;
        check_obd_ext(dir, o, keys, t)?;
    }

    if !recognised {
        return Err(
            "expected.json carries no section this runner knows how to check; \
             an unchecked vector is a gap, not a pass"
                .into(),
        );
    }
    Ok(())
}

// ── segment vectors ─────────────────────────────────────────────────────────

fn read(dir: &Path, name: &str) -> std::result::Result<Vec<u8>, String> {
    fs::read(dir.join(name)).map_err(|e| format!("read {name}: {e}"))
}

fn check_single_segment(
    dir: &Path,
    scan: &ScanExpectation,
    keyed: Option<&KeyedExpectation>,
    keys: &RootKeyProvider,
    t: &mut Tally,
) -> Check {
    let bytes = read(dir, "segment.bin")?;

    // The structural verdict: no key.
    let res = scan_segment(&bytes, ScanState::default(), None)
        .map_err(|e| format!("structural scan returned an error: {e}"))?;
    check_no_plaintext(&res)?;
    compare_scan(&res, scan, "structural: ")?;
    t.structural += 1;
    t.what.push("structural");

    match keyed {
        Some(KeyedExpectation::One(k)) => {
            check_keyed(&bytes, ScanState::default(), k, keys, "")?;
            t.keyed += 1;
            t.what.push("keyed");
            Ok(())
        }
        Some(KeyedExpectation::Many(_)) => {
            Err("a single-segment vector carries an array of keyed verdicts".into())
        }
        // Every v3 segment vector states both verdicts. One without a keyed
        // verdict would silently test only half the format.
        None => Err("segment vector has no keyed verdict".into()),
    }
}

/// A keyless scan must not hand out ciphertext dressed as a payload.
fn check_no_plaintext(res: &ScanResult) -> Check {
    if res.decrypted {
        return Err("a keyless scan reports itself as decrypted".into());
    }
    if let Some(i) = res.frames.iter().position(|f| f.payload.is_some()) {
        return Err(format!("frame {i} of a keyless scan exposes a payload"));
    }
    Ok(())
}

fn check_multi_segment(
    dir: &Path,
    segs: &[ScanExpectation],
    exp: &Expectation,
    keys: &RootKeyProvider,
    t: &mut Tally,
) -> Check {
    let keyed = match &exp.keyed {
        Some(KeyedExpectation::Many(k)) if k.len() == segs.len() => k,
        _ => {
            return Err("multi-segment vector needs one keyed verdict per segment".into());
        }
    };

    let mut bytes = Vec::with_capacity(segs.len());
    for i in 0..segs.len() {
        bytes.push(read(dir, &format!("segment-{i}.bin"))?);
    }

    // Structural and keyed chains are threaded independently: the keyed scan
    // must reach the same continuity state on its own, not borrow it from the
    // structural one.
    let mut s_state = ScanState::default();
    let mut k_state = ScanState::default();
    for (i, b) in bytes.iter().enumerate() {
        let prefix = format!("segment {i}: ");

        let res = scan_segment(b, s_state, None)
            .map_err(|e| format!("{prefix}structural scan returned an error: {e}"))?;
        check_no_plaintext(&res)?;
        compare_scan(&res, &segs[i], &format!("{prefix}structural: "))?;
        s_state = res.next;
        t.structural += 1;

        k_state = check_keyed(b, k_state, &keyed[i], keys, &prefix)?;
        t.keyed += 1;
    }
    if s_state != k_state {
        return Err(format!(
            "structural and keyed scans ended in different chain states: {s_state:?} vs {k_state:?}"
        ));
    }
    t.what.push("structural chain");
    t.what.push("keyed chain");

    // Segment 1 from the zero state must be a chain break, not a silent
    // acceptance: the capture chain runs bundle-wide.
    if let Some(z) = &exp.segment_1_from_zero_state {
        let res = scan_segment(&bytes[1], ScanState::default(), None)
            .map_err(|e| format!("segment 1 from zero: {e}"))?;
        compare_scan(&res, z, "segment 1 from the zero state: ")?;
        t.structural += 1;
        t.what.push("segment 1 from zero state");
    } else {
        return Err("multi-segment vector lacks segment_1_from_zero_state".into());
    }

    Ok(())
}

fn compare_scan(res: &ScanResult, exp: &ScanExpectation, prefix: &str) -> Check {
    if res.stop.name() != exp.stop_reason {
        return Err(format!(
            "{prefix}stop_reason = {}, want {} ({})",
            res.stop.name(),
            exp.stop_reason,
            res.stop_detail
        ));
    }
    if res.frames.len() != exp.frames_retained {
        return Err(format!(
            "{prefix}frames_retained = {}, want {}",
            res.frames.len(),
            exp.frames_retained
        ));
    }
    if res.stop_offset != exp.stop_offset {
        return Err(format!(
            "{prefix}stop_offset = {}, want {}",
            res.stop_offset, exp.stop_offset
        ));
    }
    if res.discarded_tail_bytes != exp.discarded_tail_bytes {
        return Err(format!(
            "{prefix}discarded_tail_bytes = {}, want {}",
            res.discarded_tail_bytes, exp.discarded_tail_bytes
        ));
    }
    if res.unknown_type_count != exp.unknown_type_count {
        return Err(format!(
            "{prefix}unknown_type_count = {}, want {}",
            res.unknown_type_count, exp.unknown_type_count
        ));
    }

    // Both directions: every expected count matches, and nothing was counted
    // that the expectation does not name.
    for (name, want) in &exp.record_counts {
        let got = res
            .record_counts
            .iter()
            .find(|(rt, _)| &rt.name() == name)
            .map(|(_, n)| *n)
            .unwrap_or(0);
        if got != *want {
            return Err(format!(
                "{prefix}record_counts[{name}] = {got}, want {want}"
            ));
        }
    }
    for (rt, n) in &res.record_counts {
        if !exp.record_counts.contains_key(&rt.name()) {
            return Err(format!(
                "{prefix}counted {n} {} record(s) the expectation does not name",
                rt.name()
            ));
        }
    }

    if let Some(want) = exp.first_seq {
        match res.frames.first() {
            None => return Err(format!("{prefix}expected frames, got none")),
            Some(f) if f.seq != want => {
                return Err(format!("{prefix}first_seq = {}, want {want}", f.seq));
            }
            _ => {}
        }
    }
    if let (Some(want), Some(f)) = (exp.last_seq, res.frames.last())
        && f.seq != want
    {
        return Err(format!("{prefix}last_seq = {}, want {want}", f.seq));
    }

    Ok(())
}

/// The spec's name for a keyed refusal.
fn keyed_error_name(e: &FormatError) -> Option<&'static str> {
    match e {
        FormatError::KeyVersionMismatch { .. } => Some("KEY_VERSION_MISMATCH"),
        FormatError::NoKey => Some("NO_KEY"),
        _ => None,
    }
}

/// Scan with the vector key and compare against the keyed verdict, returning
/// the continuity state for a following segment.
fn check_keyed(
    bytes: &[u8],
    state: ScanState,
    want: &KeyedVerdict,
    keys: &RootKeyProvider,
    prefix: &str,
) -> std::result::Result<ScanState, String> {
    let scanned = scan_segment(bytes, state, Some(keys as &dyn KeyProvider));

    if let Some(want_err) = &want.error {
        return match scanned {
            Err(e) if keyed_error_name(&e) == Some(want_err.as_str()) => Ok(state),
            Err(e) => Err(format!("{prefix}keyed scan error = {e}, want {want_err}")),
            Ok(r) => Err(format!(
                "{prefix}keyed scan succeeded ({}), want the refusal {want_err}",
                r.stop
            )),
        };
    }
    let res = scanned.map_err(|e| format!("{prefix}keyed scan returned an error: {e}"))?;

    // The key, independently of the scanner, so a KDF regression is reported
    // as that rather than as a puzzling tag failure.
    let want_key = want
        .segment_key_hex
        .as_deref()
        .ok_or_else(|| format!("{prefix}keyed verdict lacks segment_key_hex"))?;
    let got_key = format::hex(&derive_segment_key(&keys.root, &res.header));
    if got_key != want_key {
        return Err(format!(
            "{prefix}segment key = {got_key}, want {want_key} — HKDF derivation differs from the vector"
        ));
    }

    let want_stop = want.stop_reason.as_deref().unwrap_or_default();
    if res.stop.name() != want_stop {
        return Err(format!(
            "{prefix}keyed stop_reason = {}, want {want_stop} ({})",
            res.stop, res.stop_detail
        ));
    }
    if let Some(n) = want.frames_retained
        && res.frames.len() != n
    {
        return Err(format!(
            "{prefix}keyed frames_retained = {}, want {n}",
            res.frames.len()
        ));
    }
    if let Some(o) = want.stop_offset
        && res.stop_offset != o
    {
        return Err(format!(
            "{prefix}keyed stop_offset = {}, want {o}",
            res.stop_offset
        ));
    }
    if !res.decrypted {
        return Err(format!(
            "{prefix}keyed scan does not report itself decrypted"
        ));
    }

    // SHA-256 over, for each retained frame, u32le(plaintext length) ‖ plaintext.
    let mut h = Sha256::new();
    for (i, f) in res.frames.iter().enumerate() {
        let pt = f
            .payload
            .as_ref()
            .ok_or_else(|| format!("{prefix}keyed frame {i} carries no plaintext"))?;
        h.update((pt.len() as u32).to_le_bytes());
        h.update(pt);
    }
    let got = format::hex(&h.finalize());
    let want_digest = want.plaintext_sha256_hex.as_deref().unwrap_or_default();
    if got != want_digest {
        return Err(format!(
            "{prefix}plaintext digest = {got}, want {want_digest}"
        ));
    }

    Ok(res.next)
}

fn check_header(dir: &Path, h: &HeaderExpectation, keys: &RootKeyProvider, t: &mut Tally) -> Check {
    let bytes = read(dir, "segment.bin")?;

    // Unusable with or without a key: the header is verified before any key is
    // derived, so a corrupt header can never be reported as an auth failure.
    for keyed in [false, true] {
        let k: Option<&dyn KeyProvider> = if keyed { Some(keys) } else { None };
        match scan_segment(&bytes, ScanState::default(), k) {
            Err(FormatError::BadHeaderCrc { .. }) if h.parse_error == "bad_header_crc" => {}
            Err(e) if h.parse_error != "bad_header_crc" => {
                return Err(format!(
                    "unrecognised parse_error {:?} (got {e})",
                    h.parse_error
                ));
            }
            Err(e) => {
                return Err(format!(
                    "keyed={keyed}: header error {e}, want bad_header_crc"
                ));
            }
            Ok(_) => {
                return Err(format!(
                    "keyed={keyed}: expected a header parse error, got none"
                ));
            }
        }
    }
    t.structural += 1;
    t.keyed += 1;
    t.what.push("header refused (structural and keyed)");
    Ok(())
}

// ── manifests, binding, receipts ────────────────────────────────────────────

fn verifying_key(hex_key: &str, what: &str) -> std::result::Result<VerifyingKey, String> {
    let raw = format::unhex_array::<32>(hex_key).ok_or(format!("{what} is not 32 bytes of hex"))?;
    VerifyingKey::from_bytes(&raw).map_err(|e| format!("bad {what}: {e}"))
}

fn check_manifest(dir: &Path, m_exp: &ManifestExpectation, t: &mut Tally) -> Check {
    let encoded = read(dir, "manifest.cbor")?;
    let sig: [u8; 64] = read(dir, "manifest.sig")?
        .try_into()
        .map_err(|_| "manifest.sig is not 64 bytes".to_string())?;
    let key = verifying_key(&m_exp.device_public_key_hex, "device_public_key_hex")?;

    // The bytes must parse as canonical regardless of signature validity: a bad
    // signature does not make the encoding malformed.
    let parsed = Manifest::from_cbor(&encoded);
    match &parsed {
        Err(e) if m_exp.valid => return Err(format!("from_cbor: {e}")),
        Ok(_) if !m_exp.valid => {
            return Err("manifest parsed but the vector says it is invalid".into());
        }
        _ => {}
    }

    match verify_manifest(&encoded, &sig, &key) {
        Err(e) if m_exp.signature_valid => return Err(format!("signature should verify: {e}")),
        Ok(_) if !m_exp.signature_valid => {
            return Err("signature verified but the vector expects it to fail".into());
        }
        _ => {}
    }
    t.what.push("manifest");

    let Ok(m) = parsed else { return Ok(()) };

    let want_root = format::unhex_array::<32>(&m_exp.content_root_hex)
        .ok_or("content_root_hex is not 32 bytes of hex")?;
    if m.content_root != want_root {
        return Err(format!(
            "content_root = {}, want {}",
            format::hex(&m.content_root),
            m_exp.content_root_hex
        ));
    }
    m.verify_content_root()
        .map_err(|e| format!("verify_content_root: {e}"))?;

    // Re-encoding must reproduce the committed bytes exactly. This is the check
    // that catches an encoding divergence between implementations.
    if !m_exp.canonical_bytes_sha256_hex.is_empty() {
        let reencoded = m.to_cbor().map_err(|e| format!("to_cbor: {e}"))?;
        let got = format::hex(&Sha256::digest(&reencoded));
        if got != m_exp.canonical_bytes_sha256_hex {
            return Err(format!(
                "re-encoded manifest digest = {got}, want {} — this implementation \
                 does not produce byte-identical output",
                m_exp.canonical_bytes_sha256_hex
            ));
        }
        if reencoded != encoded {
            return Err("re-encoded manifest differs from manifest.cbor".into());
        }
        t.what.push("byte-identical re-encode");
    }

    Ok(())
}

fn check_binding(dir: &Path, b: &BindingExpectation, t: &mut Tally) -> Check {
    let m = Manifest::from_cbor(&read(dir, "manifest.cbor")?)
        .map_err(|e| format!("binding: parse manifest: {e}"))?;

    let mut members: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    for mem in &m.members {
        let bytes = read(dir, &mem.name)?;
        // The vector must itself be consistent, or a binding verdict would be
        // testing the wrong thing.
        if <[u8; 32]>::from(Sha256::digest(&bytes)) != mem.sha256
            || bytes.len() as u64 != mem.length
        {
            return Err(format!(
                "member {} does not match its manifest digest: the vector is internally inconsistent",
                mem.name
            ));
        }
        members.insert(mem.name.clone(), bytes);
    }

    let verdict =
        verify_members_against_manifest(&m, |name| members.get(name).map(|v| v.as_slice()));
    match (b.matches, verdict) {
        (true, Ok(())) => {}
        (true, Err(e)) => return Err(format!("members should match the manifest: {e}")),
        (false, Ok(())) => {
            return Err("members verified, but the vector expects a binding mismatch".into());
        }
        (false, Err(FormatError::BindingMismatch { field, .. })) => {
            if field != b.mismatched_field {
                return Err(format!(
                    "mismatch reported on {field}, want {}",
                    b.mismatched_field
                ));
            }
        }
        (false, Err(e)) => {
            return Err(format!("binding failed for the wrong reason: {e}"));
        }
    }
    t.what.push("binding");
    Ok(())
}

fn check_receipt(dir: &Path, r_exp: &ReceiptExpectation, t: &mut Tally) -> Check {
    let encoded = read(dir, "receipt.cbor")?;
    let key = verifying_key(&r_exp.server_public_key_hex, "server_public_key_hex")?;

    let r = Receipt::from_cbor(&encoded).map_err(|e| format!("from_cbor: {e}"))?;

    let want_root = format::unhex_array::<32>(&r_exp.receipt_content_root_hex)
        .ok_or("receipt_content_root_hex is not 32 bytes of hex")?;
    if r.content_root != want_root {
        return Err(format!(
            "receipt content_root = {}, want {}",
            format::hex(&r.content_root),
            r_exp.receipt_content_root_hex
        ));
    }

    let sig_ok = r.verify(&key).is_ok();
    if r_exp.signature_valid != sig_ok {
        return Err(format!(
            "signature verified = {sig_ok}, want {}",
            r_exp.signature_valid
        ));
    }

    let uploaded = format::unhex_array::<32>(&r_exp.uploaded_content_root_hex)
        .ok_or("uploaded_content_root_hex is not 32 bytes of hex")?;
    let ack_ok = r.verify_acknowledges(&key, &uploaded).is_ok();
    if r_exp.acknowledges_uploaded_root != ack_ok {
        return Err(format!(
            "accepted as an acknowledgement = {ack_ok}, want {}",
            r_exp.acknowledges_uploaded_root
        ));
    }
    t.what.push("receipt");
    Ok(())
}

// ── merkle, policy, update ──────────────────────────────────────────────────

fn check_merkle(dir: &Path, m_exp: &MerkleExpectation, t: &mut Tally) -> Check {
    // Leaves present: check the tree construction directly.
    if let Some(leaves_hex) = &m_exp.leaves_hex {
        let mut leaves = Vec::with_capacity(leaves_hex.len());
        for h in leaves_hex {
            leaves.push(format::unhex_array::<32>(h).ok_or("leaf is not 32 bytes of hex")?);
        }
        let got = format::hex(&merkle_root(&leaves));
        if got != m_exp.root_hex {
            return Err(format!("root = {got}, want {}", m_exp.root_hex));
        }
        t.what.push("merkle root");
        return Ok(());
    }

    // Otherwise a content-root vector described by members.json.
    let raw = fs::read_to_string(dir.join("members.json"))
        .map_err(|e| format!("read members.json: {e}"))?;
    let descriptors: Vec<MemberDescriptor> =
        serde_json::from_str(&raw).map_err(|e| format!("parse members.json: {e}"))?;

    let mut members = Vec::with_capacity(descriptors.len());
    for d in &descriptors {
        members.push(Member {
            name: d.name.clone(),
            length: d.length,
            sha256: format::unhex_array::<32>(&d.sha256_hex)
                .ok_or("member sha256_hex is not 32 bytes of hex")?,
        });
    }

    let root = content_root(&members).map_err(|e| format!("content_root: {e}"))?;
    let got = format::hex(&root);
    if got != m_exp.root_hex {
        return Err(format!("content root = {got}, want {}", m_exp.root_hex));
    }

    // Order independence: every rotation of the input yields the same root.
    for k in 1..members.len() {
        let mut rotated = members.clone();
        rotated.rotate_left(k);
        if content_root(&rotated).map_err(|e| e.to_string())? != root {
            return Err(format!(
                "rotating the members by {k} changed the content root"
            ));
        }
    }
    // And identity depends on content: changing one digest changes the root.
    if let Some(first) = members.first_mut() {
        first.sha256[0] ^= 1;
        if content_root(&members).map_err(|e| e.to_string())? == root {
            return Err("changing a member digest left the content root unchanged".into());
        }
    }
    t.what.push("content root");
    Ok(())
}

fn check_policy(dir: &Path, want: &PolicySnapshot, t: &mut Tally) -> Check {
    let raw = read(dir, "policy.cbor")?;
    let got = PolicySnapshot::from_cbor(&raw).map_err(|e| format!("parse policy: {e}"))?;
    if &got != want {
        return Err(format!(
            "decoded policy does not match the expectation\n got: {got:?}\nwant: {want:?}"
        ));
    }
    // The re-encode is the point: identical policy must be byte-identical.
    if got.to_cbor() != raw {
        return Err("policy re-encodes to different bytes".into());
    }
    t.what.push("policy byte-identical");
    Ok(())
}

fn check_update(dir: &Path, u: &UpdateExpectation, t: &mut Tally) -> Check {
    let encoded = read(dir, "descriptor.cbor")?;
    let sig = read(dir, "descriptor.sig")?;
    let key = verifying_key(&u.update_public_key_hex, "update_public_key_hex")?;

    let d = match (
        verify_update_descriptor(&encoded, &sig, &key),
        u.signature_valid,
    ) {
        (Ok(d), true) => d,
        (Err(e), true) => return Err(format!("descriptor should verify: {e}")),
        (Ok(_), false) => {
            return Err("descriptor verified but the vector expects refusal".into());
        }
        (Err(FormatError::BadSignature), false) => {
            // The refusal must be the signature, not a parse failure that
            // happened to coincide: the vector says the descriptor itself is
            // well formed.
            crate::format::update::UpdateDescriptor::from_cbor(&encoded)
                .map_err(|e| format!("refused, but the descriptor also fails to parse: {e}"))?;
            t.what.push("update signature refused");
            return Ok(());
        }
        (Err(e), false) => return Err(format!("refused for the wrong reason: {e}")),
    };

    if d.firmware_version != u.firmware_version {
        return Err(format!(
            "firmware_version = {:?}, want {:?}",
            d.firmware_version, u.firmware_version
        ));
    }
    if d.min_firmware_version != u.min_firmware_version {
        return Err(format!(
            "min_firmware_version = {:?}, want {:?}",
            d.min_firmware_version, u.min_firmware_version
        ));
    }
    if d.image_length != u.image_length {
        return Err(format!(
            "image_length = {}, want {}",
            d.image_length, u.image_length
        ));
    }
    if format::hex(&d.image_sha256) != u.image_sha256_hex {
        return Err(format!(
            "image_sha256 = {}, want {}",
            format::hex(&d.image_sha256),
            u.image_sha256_hex
        ));
    }
    if d.to_cbor().map_err(|e| e.to_string())? != encoded {
        return Err("descriptor re-encodes to different bytes".into());
    }
    t.what.push("update descriptor");
    Ok(())
}

// ── payload vectors (decoded from a keyed scan) ─────────────────────────────

/// Scan with the key and return the plaintexts of frames of one record type.
fn keyed_payloads(
    dir: &Path,
    keys: &RootKeyProvider,
    rt: format::RecordType,
) -> std::result::Result<Vec<Vec<u8>>, String> {
    let bytes = read(dir, "segment.bin")?;
    let res = scan_segment(&bytes, ScanState::default(), Some(keys as &dyn KeyProvider))
        .map_err(|e| format!("keyed scan: {e}"))?;
    if res.stop != StopReason::Eof {
        return Err(format!("keyed scan stopped with {}", res.stop));
    }
    Ok(res
        .frames
        .into_iter()
        .filter(|f| f.record_type == rt)
        .filter_map(|f| f.payload)
        .collect())
}

fn check_events(dir: &Path, e: &EventsExpectation, keys: &RootKeyProvider, t: &mut Tally) -> Check {
    let payloads = keyed_payloads(dir, keys, format::RecordType::TRIP_EVENT)?;
    if payloads.len() != e.events.len() {
        return Err(format!(
            "found {} events, want {}",
            payloads.len(),
            e.events.len()
        ));
    }
    for (i, (p, want)) in payloads.iter().zip(&e.events).enumerate() {
        let ev = payload::parse_trip_event(p).map_err(|err| format!("event {i}: {err}"))?;
        if ev.event_type != want.event_type
            || payload::event_type_name(ev.event_type) != want.event_type_name
            || ev.lat_e7 != want.lat_e7
            || ev.lon_e7 != want.lon_e7
            || ev.detail != want.detail
        {
            return Err(format!("event {i} = {ev:?}, want {want:?}"));
        }
        // Re-encoding must reproduce the payload, or an implementation could
        // read these records and not write them.
        if &payload::encode_trip_event(ev.event_type, ev.lat_e7, ev.lon_e7, &ev.detail) != p {
            return Err(format!("event {i} re-encodes to different bytes"));
        }
    }
    t.what.push("trip events");
    Ok(())
}

fn check_health(dir: &Path, h: &HealthExpectation, keys: &RootKeyProvider, t: &mut Tally) -> Check {
    let payloads = keyed_payloads(dir, keys, format::RecordType::DEVICE_HEALTH)?;
    if payloads.len() != h.records.len() {
        return Err(format!(
            "found {} health records, want {}",
            payloads.len(),
            h.records.len()
        ));
    }
    for (i, (p, want)) in payloads.iter().zip(&h.records).enumerate() {
        let state = payload::parse_health_state(p).map_err(|e| format!("health {i}: {e}"))?;
        if state != want.health_state {
            return Err(format!(
                "health record {i} state = {state:#04x}, want {:#04x}",
                want.health_state
            ));
        }
        let names = payload::health_state_names(state);
        if names != want.names {
            return Err(format!(
                "health record {i} named {names:?}, want {:?}",
                want.names
            ));
        }
    }
    t.what.push("health bitmap");
    Ok(())
}

fn close(got: Option<f64>, want: Option<f64>, tol: f64) -> bool {
    match (got, want) {
        (None, None) => true,
        (Some(g), Some(w)) => (g - w).abs() <= tol,
        _ => false,
    }
}

fn check_obd_ext(
    dir: &Path,
    o: &ObdExtExpectation,
    keys: &RootKeyProvider,
    t: &mut Tally,
) -> Check {
    let payloads = keyed_payloads(dir, keys, format::RecordType::OBD_EXTENDED)?;
    if payloads.len() != o.records.len() {
        return Err(format!(
            "found {} OBD_EXTENDED records, want {}",
            payloads.len(),
            o.records.len()
        ));
    }
    for (i, (p, w)) in payloads.iter().zip(&o.records).enumerate() {
        let r = payload::parse_obd_extended(p).map_err(|e| format!("record {i}: {e}"))?;
        let fields_match = r.map_kpa == w.map_kpa
            && r.maf_cgps == w.maf_cgps
            && r.lambda_e4 == w.lambda_e4
            && r.abs_load_raw == w.abs_load_raw
            && r.baro_kpa == w.baro_kpa
            && r.ambient_temp_c == w.ambient_temp_c
            && r.fuel_trim_short_pct == w.fuel_trim_short_pct
            && r.fuel_trim_long_pct == w.fuel_trim_long_pct
            && r.pids_requested == w.pids_requested
            && r.pids_answered == w.pids_answered
            && r.poll_cadence_ms == w.poll_cadence_ms;
        if !fields_match {
            return Err(format!("record {i} decoded as {r:?}, want {w:?}"));
        }
        if r.map_saturated() != w.map_saturated {
            return Err(format!(
                "record {i} map_saturated = {}, want {}",
                r.map_saturated(),
                w.map_saturated
            ));
        }
        // Absent in the expectation means uncomputable, and must be: boost
        // with no barometric reading is unknown, not a sea-level guess.
        if !close(r.boost_psi(), w.boost_psi, 0.01) {
            return Err(format!(
                "record {i} boost_psi = {:?}, want {:?}",
                r.boost_psi(),
                w.boost_psi
            ));
        }
        if !close(r.lambda(), w.lambda, 0.0001) {
            return Err(format!(
                "record {i} lambda = {:?}, want {:?}",
                r.lambda(),
                w.lambda
            ));
        }
        if !close(r.abs_load_pct(), w.abs_load_pct, 0.01) {
            return Err(format!(
                "record {i} abs_load_pct = {:?}, want {:?}",
                r.abs_load_pct(),
                w.abs_load_pct
            ));
        }
    }
    t.what.push("OBD_EXTENDED");
    Ok(())
}
