//! Emits the C header: one table set per selected profile, a catalogue of every
//! profile in engines/ (so a build can recognise a vehicle that needs an engine it was
//! not built with), and the build identity.
//!
//! Output is a pure function of the YAML bytes and the selection: no timestamps, no
//! paths, no host names, so a committed header can be diffed against a regeneration.

use std::fmt::Write;

use sha2::{Digest, Sha256};

use crate::profile::{hex, Checked, Maybe, Status, Tier};

pub const GENERATOR: &str = concat!("enginegen ", env!("CARGO_PKG_VERSION"));

fn cstr(s: &str) -> String {
    let mut o = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            c if c.is_ascii() && !c.is_control() => o.push(c),
            _ => o.push('?'),
        }
    }
    o.push('"');
    o
}

fn ident(id: &str) -> String {
    id.replace('-', "_")
}

fn bytes_lit(b: &[u8]) -> String {
    b.iter().map(|x| format!("0x{x:02x}")).collect::<Vec<_>>().join(", ")
}

/// The identity of a build: which engines, at which version, with which content.
pub struct Identity {
    pub selection: String,
    pub build_sha256: [u8; 32],
    pub string: String,
}

pub fn identity(selected: &[&Checked]) -> Identity {
    let mut h = Sha256::new();
    h.update(b"cairn.engine-build/v1-draft\n");
    let mut parts = Vec::new();
    for c in selected {
        let p = &c.profile;
        h.update(format!("{}\n{}\n{}\n", p.engine_id, p.version, hex(&c.sha256)).as_bytes());
        parts.push(format!("{}@{}/{}", p.engine_id, p.version, &hex(&c.sha256)[..16]));
    }
    let build: [u8; 32] = h.finalize().into();
    let selection = selected.iter().map(|c| c.profile.engine_id.as_str()).collect::<Vec<_>>().join(",");
    let string = format!("engines={} build={}", parts.join(","), &hex(&build)[..16]);
    Identity { selection, build_sha256: build, string }
}

// The CAIRN_K_* bits live in lib/cairn_engine/cairn_engine.h, which is the single
// definition; the generator only names them.

/// Emit the whole header for `selected` (a subset of `all`).
pub fn header(all: &[Checked], selected: &[&Checked]) -> String {
    let id = identity(selected);
    let mut o = String::new();
    let w = &mut o;

    let _ = writeln!(w, "/*");
    let _ = writeln!(w, " * GENERATED by {GENERATOR} from the engines/ YAML files. DO NOT EDIT.");
    let _ = writeln!(w, " *");
    let _ = writeln!(w, " * Regenerate with `make engines-gen` (all engines, the committed copy) or let");
    let _ = writeln!(w, " * `make firmware ENGINES=...` write the selection. A stale committed copy fails");
    let _ = writeln!(w, " * `make engines-check`.");
    let _ = writeln!(w, " *");
    let _ = writeln!(w, " * selection: {}", id.selection);
    let _ = writeln!(w, " */");
    let _ = writeln!(w, "#ifndef CAIRN_ENGINES_GEN_H");
    let _ = writeln!(w, "#define CAIRN_ENGINES_GEN_H");
    let _ = writeln!(w);
    let _ = writeln!(w, "#include \"cairn_engine.h\"");
    let _ = writeln!(w);
    let _ = writeln!(w, "#define CAIRN_ENGINES_SELECTION {}", cstr(&id.selection));
    let _ = writeln!(w, "#define CAIRN_ENGINES_COUNT {}", selected.len());
    let _ = writeln!(w, "#define CAIRN_ENGINES_CATALOGUE_COUNT {}", all.len());
    let _ = writeln!(w, "#define CAIRN_ENGINES_IDENTITY_STRING {}", cstr(&id.string));
    let _ = writeln!(w);

    for c in selected {
        let p = &c.profile;
        let n = ident(&p.engine_id);
        let _ = writeln!(w, "/* ── {} v{} ({}) ── */", p.engine_id, p.version, hex(&c.sha256));

        let pids = c.ordered_pids();
        let mut known: Vec<&str> = Vec::new();
        let mut blob: Vec<u8> = Vec::new();
        let mut rows = String::new();
        for (i, pid) in pids.iter().enumerate() {
            let off = blob.len();
            blob.extend(&c.code[i]);
            let _ = writeln!(
                rows,
                "    /* 0x{:02X} {} */ {{ .pid = 0x{:04X}, .service = 0x{:02X}, .nbytes = {}, .tier = {}, .cold_slot = {}, .field = {}, .log = {}, .scale_e = {}, .range_min = {}, .range_max = {}, .code_off = {}, .code_len = {}, .name = {}, .unit = {} }},",
                pid.id,
                pid.name,
                pid.id,
                pid.service,
                pid.bytes,
                if pid.tier == Tier::Hot { "CAIRN_TIER_HOT" } else { "CAIRN_TIER_COLD" },
                pid.cold_slot.unwrap_or(0),
                pid.field.c_name(),
                pid.log as u8,
                pid.scale,
                pid.range[0],
                pid.range[1],
                off,
                c.code[i].len(),
                cstr(&pid.name),
                cstr(&pid.unit),
            );
        }
        let n_hot = pids.iter().filter(|p| p.tier == Tier::Hot).count();
        if !pids.is_empty() {
            known.push("CAIRN_K_PIDS");
            let _ = writeln!(w, "static const uint8_t k_code_{n}[] = {{ {} }};", bytes_lit(&blob));
            let _ = writeln!(w, "static const cairn_pid_t k_pids_{n}[] = {{\n{rows}}};");
        }
        if !p.probes.is_empty() {
            let _ = writeln!(w, "static const cairn_probe_t k_probes_{n}[] = {{");
            for pr in &p.probes {
                let _ = writeln!(w, "    {{ .pid = 0x{:02X}, .std_bytes = {}, .name = {} }},", pr.id, pr.std_bytes, cstr(&pr.name));
            }
            let _ = writeln!(w, "}};");
        }

        let (mut obd_period, mut batch_period, mut cold_slots) = (0u32, 0u32, 0u32);
        if let Maybe::Known(c) = &p.cadence {
            if let Maybe::Known(v) = &c.obd_period_ms {
                obd_period = *v as u32;
                known.push("CAIRN_K_OBD_PERIOD");
            }
            if let Maybe::Known(v) = &c.obd_batch_period_ms {
                batch_period = *v as u32;
                known.push("CAIRN_K_OBD_BATCH_PERIOD");
            }
            if let Maybe::Known(v) = &c.cold_slots {
                cold_slots = *v as u32;
                known.push("CAIRN_K_COLD_SLOTS");
            }
        }
        let (mut on_mv, mut idle, mut hb, mut dv, mut dm, mut db, mut sleep) = (0u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32);
        if let Maybe::Known(ws) = &p.wake_sleep {
            macro_rules! take {
                ($f:expr, $dst:ident, $bit:expr) => {
                    if let Maybe::Known(v) = &$f {
                        $dst = *v as u32;
                        known.push($bit);
                    }
                };
            }
            take!(ws.engine_on_mv, on_mv, "CAIRN_K_ENGINE_ON_MV");
            take!(ws.standby_idle_ms, idle, "CAIRN_K_STANDBY_IDLE");
            take!(ws.standby_heartbeat_ms, hb, "CAIRN_K_STANDBY_HEARTBEAT");
            take!(ws.drive_voltage_dwell_ms, dv, "CAIRN_K_DRIVE_VOLTAGE_DWELL");
            take!(ws.drive_motion_dwell_ms, dm, "CAIRN_K_DRIVE_MOTION_DWELL");
            take!(ws.drive_both_dwell_ms, db, "CAIRN_K_DRIVE_BOTH_DWELL");
            take!(ws.bus_first_sleep_phase_ms, sleep, "CAIRN_K_BUS_SLEEP_PHASE");
        }
        let (mut smin, mut smax) = (0u32, 0u32);
        if let Maybe::Known(s) = &p.supply {
            if let Maybe::Known(r) = &s.plausible_mv {
                smin = r[0] as u32;
                smax = r[1] as u32;
                known.push("CAIRN_K_SUPPLY_RANGE");
            }
        }
        let status = match p.status {
            Status::Stub => "CAIRN_ENGINE_STUB",
            Status::Derived => "CAIRN_ENGINE_DERIVED",
            Status::Verified => "CAIRN_ENGINE_VERIFIED",
        };
        let _ = writeln!(w);
        let _ = writeln!(w, "static const cairn_engine_profile_t k_profile_{n} = {{");
        let _ = writeln!(w, "    .id = {}, .name = {}, .version = {}, .status = {},", cstr(&p.engine_id), cstr(&p.name), p.version, status);
        let _ = writeln!(w, "    .sha256 = {{ {} }},", bytes_lit(&c.sha256));
        let _ = writeln!(w, "    .known = {},", if known.is_empty() { "0".to_string() } else { known.join(" | ") });
        if pids.is_empty() {
            let _ = writeln!(w, "    .pids = NULL, .n_pids = 0, .n_hot = 0, .code = NULL,");
        } else {
            let _ = writeln!(w, "    .pids = k_pids_{n}, .n_pids = {}, .n_hot = {}, .code = k_code_{n},", pids.len(), n_hot);
        }
        let _ = writeln!(w, "    .cold_slots = {cold_slots}, .obd_period_ms = {obd_period}, .obd_batch_period_ms = {batch_period},");
        let _ = writeln!(w, "    .engine_on_mv = {on_mv}, .standby_idle_ms = {idle}u, .standby_heartbeat_ms = {hb}u,");
        let _ = writeln!(w, "    .drive_voltage_dwell_ms = {dv}u, .drive_motion_dwell_ms = {dm}u, .drive_both_dwell_ms = {db}u,");
        let _ = writeln!(w, "    .bus_first_sleep_phase_ms = {sleep}u, .supply_min_mv = {smin}, .supply_max_mv = {smax},");
        if p.probes.is_empty() {
            let _ = writeln!(w, "    .probes = NULL, .n_probes = 0,");
        } else {
            let _ = writeln!(w, "    .probes = k_probes_{n}, .n_probes = {},", p.probes.len());
        }
        let _ = writeln!(w, "}};");
        let _ = writeln!(w);
    }

    let _ = writeln!(w, "static const cairn_engine_profile_t *const k_engine_profiles[] = {{");
    for c in selected {
        let _ = writeln!(w, "    &k_profile_{},", ident(&c.profile.engine_id));
    }
    let _ = writeln!(w, "}};");
    let _ = writeln!(w);

    // The catalogue lists every engine the repository knows, installed or not, so a
    // vehicle that needs an engine this build left out can still be recognised.
    for c in all {
        let n = ident(&c.profile.engine_id);
        if let Maybe::Known(v) = &c.profile.applies_to.vin_patterns {
            let _ = writeln!(w, "static const char *const k_vin_{n}[] = {{");
            for p in v {
                let _ = writeln!(w, "    {},", cstr(p));
            }
            let _ = writeln!(w, "}};");
        }
        if let Some(codes) = &c.profile.applies_to.engine_codes {
            let _ = writeln!(w, "static const char *const k_ecode_{n}[] = {{");
            for code in codes {
                let _ = writeln!(w, "    {},", cstr(code));
            }
            let _ = writeln!(w, "}};");
        }
    }
    let _ = writeln!(w, "static const cairn_engine_catalogue_entry_t k_engine_catalogue[] = {{");
    for c in all {
        let n = ident(&c.profile.engine_id);
        let inst = selected.iter().any(|s| s.profile.engine_id == c.profile.engine_id);
        let (vp, nv) = match &c.profile.applies_to.vin_patterns {
            Maybe::Known(v) => (format!("k_vin_{n}"), v.len()),
            Maybe::Unknown => ("NULL".to_string(), 0),
        };
        let (ec, ne) = match &c.profile.applies_to.engine_codes {
            Some(v) if !v.is_empty() => (format!("k_ecode_{n}"), v.len()),
            _ => ("NULL".to_string(), 0),
        };
        let _ = writeln!(w, "    {{ .id = {}, .vin_patterns = {vp}, .n_vin_patterns = {nv}, .engine_codes = {ec}, .n_engine_codes = {ne}, .installed = {} }},", cstr(&c.profile.engine_id), inst as u8);
    }
    let _ = writeln!(w, "}};");
    let _ = writeln!(w);
    let _ = writeln!(w, "static const cairn_engine_identity_t k_engine_identity = {{");
    let _ = writeln!(w, "    .selection = CAIRN_ENGINES_SELECTION,");
    let _ = writeln!(w, "    .count = CAIRN_ENGINES_COUNT,");
    let _ = writeln!(w, "    .build_sha256 = {{ {} }},", bytes_lit(&id.build_sha256));
    let _ = writeln!(w, "    .string = CAIRN_ENGINES_IDENTITY_STRING,");
    let _ = writeln!(w, "}};");
    let _ = writeln!(w);
    let _ = writeln!(w, "#endif /* CAIRN_ENGINES_GEN_H */");
    o
}
